// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjXsxf5VzqGpGVFTGZQCK9EBdqPHfaUAU',
    appId: '1:233874390433:web:6c54bed7a12b83eb731fe0',
    messagingSenderId: '233874390433',
    projectId: 'chat-group-b3ff5',
    authDomain: 'chat-group-b3ff5.firebaseapp.com',
    storageBucket: 'chat-group-b3ff5.appspot.com',
    measurementId: 'G-4ZK1QFK7V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpIZ9aYfV67pzHYd42i7lCrIvYF6kDsEs',
    appId: '1:233874390433:android:b7f6a0a488ae2c45731fe0',
    messagingSenderId: '233874390433',
    projectId: 'chat-group-b3ff5',
    storageBucket: 'chat-group-b3ff5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-1X8anUBcEgul8xmTHe1AZ3EWLxkFp8',
    appId: '1:233874390433:ios:b8a2e4f1e28453e1731fe0',
    messagingSenderId: '233874390433',
    projectId: 'chat-group-b3ff5',
    storageBucket: 'chat-group-b3ff5.appspot.com',
    iosClientId: '233874390433-s8l1hao5cs2a7u014bh7hocef1bof41f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv-1X8anUBcEgul8xmTHe1AZ3EWLxkFp8',
    appId: '1:233874390433:ios:b8a2e4f1e28453e1731fe0',
    messagingSenderId: '233874390433',
    projectId: 'chat-group-b3ff5',
    storageBucket: 'chat-group-b3ff5.appspot.com',
    iosClientId: '233874390433-s8l1hao5cs2a7u014bh7hocef1bof41f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGroup',
  );
}
